### PR TITLE
Moved the testing code to the dev profile

### PR DESCRIPTION
**Pull request by ducky427**
The previous version was broken for the production profile. No the testing is not available in the production profile.

### CODE REVIEW

**Comment by ducky427** [comment]
Thanks!

**Comment by yogthos** [comment]
I'll push out a new version tonight with the fix

**Comment by ducky427** [comment]
cheers!

**Comment by yogthos** [comment]
ok latest and greatest is up on Clojars, and I also fixed history hook to not be loaded each time changes are pushed with figwheel

**Comment by ducky427** [comment]
Looks great!

**Pull request merged**
