### PR TITLE
Startup tweaks

### PR DESCRIPTION
**Pull request by tjg**
Hi!

I just started using Reagent and studied your template. Two things helped me:

- In project.clj, investigated `:scope "provided"`. Googling found [advice from Phil Hagelberg](http://librelist.com/browser//leiningen/2014/9/7/clarifications-about-scope-in-dependencies/#32fcd639eb09c94545bec6a56c200167) to rather put it in `:profile :dev`. (Dunno if you have an overriding reason.)

- After changing `core.cljs`, re-running `lein figwheel` typically spewed an infinite loop of error messages. `lein do clean, figwheel` fixed this.

Disclaimer: I'm neither a lein nor a cljs expert. :)

### CODE REVIEW

**Comment by yogthos** [comment]
Thanks, that looks good to me. There wasn't a particular rain to use provided, so moving cljs dev makes sense and sounds like clean helps avoid odd behaviors. :-)

**Comment by yogthos** [comment]
Looks like there is a reason to use `:scope "provided"` without it building an uberjar will produce a lot of warnings. Going to roll that change back.

**Comment by tjg** [comment]
Argh! My apologies for not testing more carefully. :( Will do so in the future.

**Comment by yogthos** [comment]
no worries, it looked reasonable enough but seems like profiles aren't quite as straight forward as one would expect :)

**Pull request merged**
