### PR TITLE
Less profile

### PR DESCRIPTION
**Pull request by petrvolny**
Hi,
I've tried to integrate the template with `lein-less` and create the new `+less` profile. I tested the implementation and it (partly) works :)
I managed to have a nice dev env when runing `lein-figwheel` and `lein less auto` separately. The last thing I was not able to implement was auto compiling less files with just running `lein figwheel`. Any help? :)

Related to: #47

### CODE REVIEW

**Comment by yogthos** [comment]
Looks good so far, you probably have to create a hook using [lein-less](https://github.com/montoux/lein-less), something like `:hooks [leiningen.less]` would watch for changes and trigger less recompile that should generate new css that figwheel will reload.

**Comment by petrvolny** [comment]
Thanks for the tip! I've tried to put the hook pretty much everywhere but with no effect. The less auto-compile feature only worked with the `lein ring server` task but not with the `lein figwheel`.
I've also tried the feature on chestnut but wasn't able make it auto-compile less files either.

Maybe I am overlooking something trivial. I've found plugin called [lein-cascade](https://github.com/kumarshantanu/lein-cascade) which might be handy in triggering tasks cascade style but I am not sure if it is a good fit for this problem. Please, let me know what do you think.

**Comment by yogthos** [comment]
I think what's happening is that the less hook runs only once a profile is loaded, but doesn't stick around to watch for changes. Since figwheel's not aware of less files it doesn't trigger any recompiles. Perhaps using [lein-auto](https://github.com/weavejester/lein-auto) together with lein-less might work.

If you start lein-auto in the :dev profile and then it should call lein-less that would compile the less assets and that in turn should generate new css that figwheel will reload.

**Comment by petrvolny** [comment]
Sorry for a little delay. I tried the `lein-auto` solution but still cannot get rid of the fact that I need to run `lein auto` separately after running `lein figwheel`. Still no clue how to integrate a separate lein task with figwheel :(

**Comment by yogthos** [comment]
I think running both `lein-auto` and `lein-figwheel` might be the best case scenario. I looked at the [chestnut](https://github.com/plexus/chestnut) template for Om, and it doesn't solve the problem either from what I can tell.

**Comment by petrvolny** [comment]
Ok, so now it works in a way that you need to run `lein figwheel` and `lein less auto` separately to automatically compile less files to css. Is it ok for you?

**Comment by yogthos** [comment]
I think that's a reasonable solution, if you update the pr so it automerges, I can push out a new release with the changes. :)

**Comment by petrvolny** [comment]
Done :)

**Comment by yogthos** [comment]
ok latest and greatest up on clojars, thanks for the pr :)

**Comment by petrvolny** [comment]
Thanks for your guidence on this one ;)

**Comment by yogthos** [comment]
@petrvolny so I just found out about [lein-pdo](https://github.com/Raynes/lein-pdo/blob/master/src/leiningen/pdo.clj) that solves the problem. With it you can create an alias like:

```clojure
:aliases {"dev"  ["pdo" "less" " "auto," "figwheel"]}
```
and it'll start both tasks in parallel

**Pull request merged**
