### PR TITLE
Update to latest Figwheel and other dependencies. Make new projects pass lein check.

### PR DESCRIPTION
**Pull request by kenrestivo**
Makes  new projects pass "lein check" and "lein ancient" without errors.

### CODE REVIEW

**Comment by yogthos** [comment]
Are all the exclusions there just for lein check, I don't think it makes much difference in term of working with the project, but makes the project definition a bit noisier. Is there a specific benefit for doing that?

**Comment by kenrestivo** [comment]
The reason is to make lein check less noisy :) It's very noisy without them, And also to make the dependencies explicit and precise and predictable instead of the result of random interactions. It also provides the most recent version of some of the dependencies. Without these, in many cases an older version of some library overrides a newer version.

The least noisy fix for everyone might be for some projects like figwheel that have old dependencies to update their dependencies. I might submit an issue for them as well.

**Comment by yogthos** [comment]
Sounds good, if the upstream projects update then it would be nice to prune this at some point.

**Comment by yogthos** [comment]
Hmm the update seems to generate a broken `project.clj` file, could you fix that up.

**Comment by kenrestivo** [comment]
Ack, fixing now. Will push in a few. Thanks!

**Comment by kenrestivo** [comment]
OK I updated them. I'll make a pull request for figwheel to update their dependencies as well.

**Comment by yogthos** [comment]
ok great, and I think you'll have to do a new pr since this one's already merged in

**Pull request merged**
