### PR TITLE
fix issues when test cljs

### PR DESCRIPTION
**Pull request by zjhmale**
if we don't use the deprecated project [clojurescript.test](https://github.com/cemerick/clojurescript.test), it's will emit a error when `lein cljsbuild test`

```
Invalid :test-command, contains non-string value: [phantomjs :runner test/vendor/es5-shim.js test/vendor/es5-sham.js test/vendor/console-polyfill.js target/test.js]
```

### CODE REVIEW

**Comment by yogthos** [comment]
There should be a way to get this running without falling back to the deprecated project though.

**Comment by zjhmale** [comment]
ok let me find a way to running without falling back to the deprecated project

**Comment by yogthos** [comment]
great, thanks for spearheading this

**Comment by waterlink** [comment]
I have figured it out. I will create a gist and post a link here later today. It actually would involve vendoring a couple of JS shims and phantom runner script.

**Comment by gadfly361** [comment]
FWIW, I've been using [doo](https://github.com/bensu/doo) without complaints. I was previously using shims, but doo takes care of it for you can can run on multiple js environments.

**Comment by waterlink** [comment]
@gadfly361 Oh, that is very good example. In my honest opinion, this setup should be generated by `+test` here.

**Comment by yogthos** [comment]
that seems reasonable to me

**Comment by zjhmale** [comment]
using `speclj` maybe a good solution, i figured it out yestoday and used in my project, i will push codes to this pull request today lately.

**Comment by zjhmale** [comment]
@yogthos @waterlink @gadfly361  now use `speclj` to do the unit test, and i `lein install` in my local env and everything works fine.

**Comment by gadfly361** [comment]
@zjhmale This is sweet!  After removing the clojurescript.test plugin, this ran for me (`lein cljsbuild test unit`).

@yogthos If you decide to invclude, I wonder if this should go in `+test` or if it should be a separate option like `+spec` (and keep `+test` for vanilla cljs.test)

**Comment by yogthos** [comment]
I think if this works more reliably then might make sense to default to specj then.

**Comment by zjhmale** [comment]
@gadfly361 remove the deprecated plugin away, and  `+spec` option is a good idea, i will working on that today.
@yogthos use speclj is reliable enought, add a `+spec` option and keep using `cljs.test` with `+test` option is more reasonable i think.

**Comment by yogthos** [comment]
sounds good to me, let's go with the `+spec` option

**Comment by waterlink** [comment]
:+1: for `+spec` version.

Though `+test` version will stay broken in this case. But that is OK, I will create a PR to fix it then later.

**Comment by zjhmale** [comment]
@yogthos @waterlink @gadfly361 `+spec` option is freeze.

**Comment by waterlink** [comment]
:+1:

**Comment by yogthos** [comment]
looks like everything's in order, I'll merge and push the new template out? :)

**Comment by zjhmale** [comment]
@yogthos yes it's ready for merge, i tested the new template and everything works fine.

**Comment by yogthos** [comment]
nice work getting this working everybody :+1:

**Comment by zjhmale** [comment]
you are welcome :)

**Comment by yogthos** [comment]
and all the latest should be up on Clojars

**Pull request merged**
