### PR TITLE
testing with cljs.test, doo and phantomjs

### PR DESCRIPTION
**Pull request by zjhmale**
in #98 we disscussed use [doo](https://github.com/bensu/doo) to fix `+test` option issue half month ago, and i think it's time to get it done.

@yogthos @gadfly361 

For reference:
https://github.com/reagent-project/reagent-cookbook/tree/master/recipes/test-example
https://github.com/Day8/re-frame-template/commit/36d2fbb3306acfdad65bc37e14374150acfe0b75

thx @gadfly361 inspired me.

### CODE REVIEW

**Comment by yogthos** [comment]
looks great :+1:

**Comment by zjhmale** [comment]
cool!

**Comment by yogthos** [comment]
just a heads up, I ended up moving test dependencies/plugins to :dev profile as they shouldn't be included in the prod build :)

**Comment by zjhmale** [comment]
ok it's fine.

**Pull request merged**
